// Curated POIs and restaurants for Morocco & Portugal trip
// All addresses verified. Photos from Wikimedia Commons.

export const DESTINATIONS = [
  { id: 'marrakech', label: 'Marrakech', country: 'Morocco', emoji: '🇲🇦' },
  { id: 'lisbon', label: 'Lisbon', country: 'Portugal', emoji: '🇵🇹' },
  { id: 'sintra', label: 'Sintra', country: 'Portugal', emoji: '🏰' },
  { id: 'porto', label: 'Porto', country: 'Portugal', emoji: '🍷' },
  { id: 'douro', label: 'Douro Valley', country: 'Portugal', emoji: '🍇' },
];

export const POIS = {
  marrakech: [
    { id: 'mk-jemaa', name: 'Jemaa el-Fna', type: 'Square / UNESCO Site', neighborhood: 'Medina', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Marrakech_-_Jemaa_el_Fna.jpg/800px-Marrakech_-_Jemaa_el_Fna.jpg', description: 'The beating heart of Marrakech and a UNESCO World Heritage site. Quieter in the morning. At dusk, it transforms into an outdoor theater of food stalls, musicians, and storytellers. Skip the snake charmers.', address: 'Jemaa el-Fnaa, Marrakech 40000, Morocco', bestTime: 'Sunset and after dark' },
    { id: 'mk-bahia', name: 'Bahia Palace', type: 'Historic Palace', neighborhood: 'Medina', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Bahia_Palace_-_Marrakesh.jpg/800px-Bahia_Palace_-_Marrakesh.jpg', description: '19th-century palace with stunning zellige tilework, carved cedar ceilings, and tranquil courtyards. Built for a grand vizier and his four wives. Less crowded than Jardin Majorelle.', address: 'Avenue Imam El Ghazali, Marrakech 40000, Morocco', bestTime: 'Mid-morning (opens 9 AM)' },
    { id: 'mk-majorelle', name: 'Jardin Majorelle', type: 'Garden / YSL Museum', neighborhood: 'Gueliz', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Jardin_Majorelle.jpg/800px-Jardin_Majorelle.jpg', description: 'Cobalt-blue villa and lush botanical garden created by Jacques Majorelle, restored by Yves Saint Laurent. Contains the Berber Museum. Book timed entry online in advance.', address: 'Rue Yves Saint Laurent, Marrakech 40090, Morocco', bestTime: 'First entry slot (8:30 AM)' },
    { id: 'mk-koutoubia', name: 'Koutoubia Mosque', type: 'Mosque (Exterior)', neighborhood: 'Medina', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Koutoubia_Mosque_Marrakesh.jpg/800px-Koutoubia_Mosque_Marrakesh.jpg', description: '12th-century mosque with a 77-meter minaret dominating the skyline. Closed to non-Muslims, but the surrounding gardens are beautiful. Especially striking at sunset.', address: 'Avenue Mohammed V, Marrakech 40000, Morocco', bestTime: 'Sunset for photos' },
    { id: 'mk-benyoussef', name: 'Medersa Ben Youssef', type: 'Historic School', neighborhood: 'Medina', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Ben_Youssef_Madrasa%2C_Marrakech.jpg/800px-Ben_Youssef_Madrasa%2C_Marrakech.jpg', description: '14th-century Islamic college, recently restored. Stunning Moorish architecture with intricate carved cedar, marble, and stucco around a central courtyard pool.', address: 'Rue Assouel, Marrakech 40000, Morocco', bestTime: 'Early afternoon for best light' },
    { id: 'mk-saadian', name: 'Saadian Tombs', type: 'Historic Tombs', neighborhood: 'Kasbah', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Marrakech-Tombeaux_saadiens_%2812%29.JPG/800px-Marrakech-Tombeaux_saadiens_%2812%29.JPG', description: 'Royal necropolis from the late 16th century, sealed and forgotten until 1917. Holds 60+ graves of the Saadi dynasty in elaborately decorated chambers. 30-minute visit.', address: 'Rue de la Kasbah, Marrakech 40000, Morocco', bestTime: 'Combine with Bahia Palace' },
    { id: 'mk-souks', name: 'Souks of the Medina', type: 'Markets', neighborhood: 'Medina', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Marrakech_souk.jpg/800px-Marrakech_souk.jpg', description: 'Kilometers of covered markets, each specializing: Souk Semmarine (textiles), Souk des Teinturiers (dyers, hanging colored wool), Souk Haddadine (blacksmiths). Negotiate hard, start at 1/3.', address: 'Souk Semmarine, Marrakech 40000, Morocco', bestTime: 'Mid-morning, avoid Friday afternoon' },
    { id: 'mk-jardin-secret', name: 'Le Jardin Secret', type: 'Garden', neighborhood: 'Medina', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Le_Jardin_Secret_Marrakech.jpg/800px-Le_Jardin_Secret_Marrakech.jpg', description: 'Restored 19th-century palace with two contrasting gardens: an exotic global one and a traditional Islamic Persian-style one. A peaceful escape with a tower offering city views.', address: '121 Rue Mouassine, Marrakech 40000, Morocco', bestTime: 'Late afternoon for warm light' },
    { id: 'mk-dar-elbacha', name: 'Dar el Bacha (Musée des Confluences)', type: 'Palace Museum', neighborhood: 'Medina', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Dar_El_Bacha_Marrakech.jpg/800px-Dar_El_Bacha_Marrakech.jpg', description: 'Former governor\'s palace now a museum exploring the meeting of cultures. Stunning architecture. Don\'t miss the on-site Bacha Coffee House with 40+ brews.', address: 'Rue Fatima Zohra, Marrakech 40000, Morocco', bestTime: 'Combine with coffee at Bacha' },
    { id: 'mk-anima', name: 'ANIMA Garden', type: 'Art Garden', neighborhood: 'Outside city', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/ANIMA_Andre_Heller.jpg/800px-ANIMA_Andre_Heller.jpg', description: 'André Heller\'s magical botanical art garden 30 minutes from the city. Tropical plants, sculptures, water features. Free shuttle from the city center.', address: 'Km 12, Route de l\'Ourika, Marrakech, Morocco', bestTime: 'Mid-morning, allow half a day' },
  ],
  lisbon: [
    { id: 'ls-jeronimos', name: 'Jerónimos Monastery', type: 'Monastery / UNESCO', neighborhood: 'Belém', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Mosteiro_dos_Jer%C3%B3nimos_em_Bel%C3%A9m.JPG/800px-Mosteiro_dos_Jer%C3%B3nimos_em_Bel%C3%A9m.JPG', description: 'Magnificent 16th-century monastery, funded by the 5% spice trade tax. Manueline architecture at its most ornate. Vasco da Gama is buried here. Book tickets online.', address: 'Praça do Império 1400-206 Lisboa, Portugal', bestTime: 'Right at opening (9:30 AM)' },
    { id: 'ls-belem-tower', name: 'Belém Tower', type: 'Fortress / UNESCO', neighborhood: 'Belém', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Torre_Belem_April_2009-4a.jpg/800px-Torre_Belem_April_2009-4a.jpg', description: '16th-century Manueline fortress on the Tagus, one of the few buildings to survive the 1755 earthquake. The interior is small with narrow stairs — the exterior is the icon.', address: 'Av. Brasília, 1400-038 Lisboa, Portugal', bestTime: 'Sunset for photos' },
    { id: 'ls-pasteis-belem', name: 'Pastéis de Belém', type: 'Historic Bakery', neighborhood: 'Belém', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Pasteis_de_Belem_Lisbon.jpg/800px-Pasteis_de_Belem_Lisbon.jpg', description: 'The original pastel de nata, baked since 1837 from a secret recipe. Don\'t skip due to the queue — it moves fast. Use the middle door for dine-in. Eat warm with cinnamon.', address: 'R. de Belém 84-92, 1300-085 Lisboa, Portugal', bestTime: 'Early morning to avoid lines' },
    { id: 'ls-castelo', name: 'Castelo de São Jorge', type: 'Castle / Viewpoint', neighborhood: 'Alfama', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Castelo_de_S%C3%A3o_Jorge_-_Lisboa.jpg/800px-Castelo_de_S%C3%A3o_Jorge_-_Lisboa.jpg', description: 'Moorish castle perched above the city, captured by Christian Crusaders in 1147. Best panoramic views of Lisbon. Wandering peacocks roam the grounds.', address: 'R. de Santa Cruz, 1100-129 Lisboa, Portugal', bestTime: 'Late afternoon for golden hour' },
    { id: 'ls-alfama', name: 'Alfama District', type: 'Historic Neighborhood', neighborhood: 'Alfama', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Alfama_Lisbon_view.jpg/800px-Alfama_Lisbon_view.jpg', description: 'Lisbon\'s oldest district, the only one to survive the 1755 earthquake. Narrow Moorish streets, fado bars, miradouros, and tiny tavernas. Get lost on purpose.', address: 'Largo do Chafariz de Dentro, 1100-139 Lisboa, Portugal', bestTime: 'Late afternoon into evening' },
    { id: 'ls-tram28', name: 'Tram 28', type: 'Historic Tram', neighborhood: 'Multiple', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Lisbon_tram_28_in_Graca.JPG/800px-Lisbon_tram_28_in_Graca.JPG', description: 'Vintage 1930s yellow tram running through Lisbon\'s steepest historic neighborhoods. Catch it at Martim Moniz to get a seat. Watch for pickpockets.', address: 'Martim Moniz, 1100-341 Lisboa, Portugal', bestTime: 'Early morning weekday' },
    { id: 'ls-discoveries', name: 'Padrão dos Descobrimentos', type: 'Monument', neighborhood: 'Belém', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Pad_descobrimentos_apr_07.jpg/800px-Pad_descobrimentos_apr_07.jpg', description: 'Modernist 1960 monument shaped like a ship\'s prow, depicting 33 figures from the Age of Discovery. Take the elevator to the top for sweeping views.', address: 'Av. Brasília, 1400-038 Lisboa, Portugal', bestTime: 'Combine with Jerónimos and Belém Tower' },
    { id: 'ls-lx-factory', name: 'LX Factory', type: 'Creative Quarter', neighborhood: 'Alcântara', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/LX_Factory_Lisboa.jpg/800px-LX_Factory_Lisboa.jpg', description: 'Former 19th-century industrial complex turned creative hub. Independent shops, the famous Ler Devagar bookstore with bicycles flying overhead, restaurants, street art.', address: 'R. Rodrigues de Faria 103, 1300-501 Lisboa, Portugal', bestTime: 'Sunday afternoon' },
    { id: 'ls-time-out', name: 'Time Out Market', type: 'Food Hall', neighborhood: 'Cais do Sodré', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Mercado_da_Ribeira_Lisboa.jpg/800px-Mercado_da_Ribeira_Lisboa.jpg', description: 'Curated food hall with stalls from 30+ of Lisbon\'s best chefs. A way to sample the food scene without committing. Crowded — go off-peak.', address: 'Av. 24 de Julho 49, 1200-479 Lisboa, Portugal', bestTime: 'Lunch on a weekday' },
    { id: 'ls-maat', name: 'MAAT', type: 'Modern Museum', neighborhood: 'Belém', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/MAAT_-_Lisbon%2C_Portugal.jpg/800px-MAAT_-_Lisbon%2C_Portugal.jpg', description: 'Striking riverside museum in a former power station and a sleek wave-shaped new building. Walk the rooftop for panoramic Tagus views. Excellent sunset spot.', address: 'Av. Brasília, 1300-598 Lisboa, Portugal', bestTime: 'Late afternoon into sunset' },
  ],
  sintra: [
    { id: 'sn-pena', name: 'Pena Palace', type: 'Royal Palace', neighborhood: 'Sintra', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Palacio_da_Pena13.jpg/800px-Palacio_da_Pena13.jpg', description: 'Wildly colorful 19th-century Romantic palace on a misty hilltop. Yellow and red towers, Moorish arches, mythological gargoyles. The most photographed spot in Portugal. Book in advance.', address: 'Estrada da Pena, 2710-609 Sintra, Portugal', bestTime: 'First entry slot (9:30 AM)' },
    { id: 'sn-regaleira', name: 'Quinta da Regaleira', type: 'Estate / Gardens', neighborhood: 'Sintra', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Quinta_da_Regaleira_-_Sintra%2C_Portugal_%2814091844551%29.jpg/800px-Quinta_da_Regaleira_-_Sintra%2C_Portugal_%2814091844551%29.jpg', description: 'Mystical estate with Masonic-Templar symbolism, grottoes, fountains, and the Initiation Well — a 27-meter inverted spiral tower descending underground. Atmospheric in mist.', address: 'R. Barbosa du Bocage 5, 2710-567 Sintra, Portugal', bestTime: 'Mid-morning, allow 2-3 hours' },
    { id: 'sn-moorish', name: 'Moorish Castle', type: 'Castle Ruins', neighborhood: 'Sintra', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Castelo_dos_Mouros%2C_Sintra.jpg/800px-Castelo_dos_Mouros%2C_Sintra.jpg', description: '8th-century Moorish hilltop fortress with crenellated walls. Less crowded than Pena, with arguably better views over Sintra and the Atlantic. Wear proper shoes.', address: 'Castelo dos Mouros, 2710-405 Sintra, Portugal', bestTime: 'Combine with Pena Palace' },
    { id: 'sn-monserrate', name: 'Monserrate Palace', type: 'Palace / Gardens', neighborhood: 'Sintra', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Palacio_de_Monserrate_-_Sintra.jpg/800px-Palacio_de_Monserrate_-_Sintra.jpg', description: 'Romantic 19th-century palace with delicate Moorish-Indian-Gothic architecture, set in 30 hectares of botanical gardens. Far less crowded than Pena.', address: 'R. Visconde de Monserrate, 2710-405 Sintra, Portugal', bestTime: 'After lunch' },
    { id: 'sn-cabo-roca', name: 'Cabo da Roca', type: 'Atlantic Cliffs', neighborhood: 'Near Sintra', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Cabo_da_Roca_2.jpg/800px-Cabo_da_Roca_2.jpg', description: 'Westernmost point of continental Europe. Dramatic cliffs, lighthouse, and a stone monument inscribed with poet Camões\' words. Free. Bring layers — windy.', address: 'Estrada do Cabo da Roca, 2705-001 Colares, Portugal', bestTime: 'Late afternoon for moody light' },
  ],
  porto: [
    { id: 'po-livraria', name: 'Livraria Lello', type: 'Historic Bookstore', neighborhood: 'Centro', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Livraria_Lello_Porto.jpg/800px-Livraria_Lello_Porto.jpg', description: '1906 art nouveau bookstore with a curved red staircase, allegedly an inspiration for Harry Potter. Entry fee credits toward book purchase. Book a timed slot.', address: 'R. das Carmelitas 144, 4050-161 Porto, Portugal', bestTime: 'First slot of the day' },
    { id: 'po-ribeira', name: 'Ribeira District', type: 'Historic Riverfront / UNESCO', neighborhood: 'Ribeira', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Ribeira_Porto_view.jpg/800px-Ribeira_Porto_view.jpg', description: 'Colorful waterfront district along the Douro. Narrow medieval streets, fishermen\'s houses, views across to the port wine cellars in Gaia. The visual postcard of Porto.', address: 'Praça da Ribeira, 4050-513 Porto, Portugal', bestTime: 'Late afternoon golden hour' },
    { id: 'po-luis', name: 'Dom Luís I Bridge', type: 'Bridge / Viewpoint', neighborhood: 'Ribeira / Gaia', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Ponte_Luis_I_Porto.jpg/800px-Ponte_Luis_I_Porto.jpg', description: 'Double-deck iron bridge designed by a student of Eiffel, 1886. Walk the upper deck for the best panoramic view. Connects Porto to the port wine cellars.', address: 'Ponte Luís I, Porto, Portugal', bestTime: 'Sunset' },
    { id: 'po-clerigos', name: 'Torre dos Clérigos', type: 'Bell Tower', neighborhood: 'Centro', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Torre_dos_Clerigos_Porto.jpg/800px-Torre_dos_Clerigos_Porto.jpg', description: '18th-century baroque bell tower, 75 meters tall. Climb 240 steps for one of the best views of Porto. Adjoining church also worth a look.', address: 'R. de São Filipe de Nery, 4050-546 Porto, Portugal', bestTime: 'Hour before sunset' },
    { id: 'po-sao-bento', name: 'São Bento Station', type: 'Train Station', neighborhood: 'Centro', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Estacao_Sao_Bento_Porto.jpg/800px-Estacao_Sao_Bento_Porto.jpg', description: 'Working train station with an entrance hall covered in 20,000+ azulejo tiles depicting Portuguese history. One of the most beautiful stations in the world. Free.', address: 'Praça de Almeida Garrett, 4000-069 Porto, Portugal', bestTime: 'Anytime, less crowded mornings' },
    { id: 'po-gaia', name: 'Vila Nova de Gaia (Port Wine Cellars)', type: 'Wine District', neighborhood: 'Gaia', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Porto_wine_cellars.jpg/800px-Porto_wine_cellars.jpg', description: 'Historic port wine cellars on the southern bank of the Douro. Tour and taste at houses like Graham\'s, Taylor\'s, Sandeman, or Cálem. Tours run €15-30.', address: 'Av. de Diogo Leite, 4400-111 Vila Nova de Gaia, Portugal', bestTime: 'Afternoon, walk across Luís I bridge' },
    { id: 'po-bolsa', name: 'Palácio da Bolsa', type: 'Historic Palace', neighborhood: 'Ribeira', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Palacio_da_Bolsa_Porto.jpg/800px-Palacio_da_Bolsa_Porto.jpg', description: '19th-century neoclassical palace built for the city\'s merchants. The Arab Room is the highlight — Moorish-revival opulence inspired by the Alhambra. Guided tours only.', address: 'R. de Ferreira Borges, 4050-253 Porto, Portugal', bestTime: 'Mid-morning' },
    { id: 'po-foz', name: 'Foz do Douro', type: 'Atlantic Coast', neighborhood: 'Foz', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Farol_da_Foz_do_Douro.jpg/800px-Farol_da_Foz_do_Douro.jpg', description: 'Where the Douro meets the Atlantic. Walk or bike from Ribeira along the river to the ocean (~5 km, flat). Lighthouse, beachfront cafes, old fortress.', address: 'Av. do Brasil, 4150-153 Porto, Portugal', bestTime: 'Late afternoon walk to sunset' },
  ],
  douro: [
    { id: 'dv-pinhao', name: 'Pinhão Village', type: 'Wine Country Town', neighborhood: 'Cima Corgo', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Pinh%C3%A3o_-_Douro.jpg/800px-Pinh%C3%A3o_-_Douro.jpg', description: 'The heart of port wine country, surrounded by terraced vineyards rising from the river. Famous train station covered in azulejo tiles depicting the harvest.', address: 'Pinhão, 5085-201, Portugal', bestTime: 'Stay overnight for early morning vineyards' },
    { id: 'dv-quinta-roeda', name: 'Quinta da Roêda (Croft)', type: 'Port Wine Estate', neighborhood: 'Pinhão', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Quinta_da_Roeda.jpg/800px-Quinta_da_Roeda.jpg', description: 'One of the most famous quintas, owned by Croft (port house since 1588). Tours include vineyard walk and tastings. Small wine bar overlooking the river.', address: 'Quinta da Roêda, 5085-201 Pinhão, Portugal', bestTime: 'Morning + boat ride' },
    { id: 'dv-quinta-seixo', name: 'Quinta do Seixo (Sandeman)', type: 'Port Wine Estate', neighborhood: 'Valença do Douro', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Quinta_do_Seixo_Sandeman.jpg/800px-Quinta_do_Seixo_Sandeman.jpg', description: 'Sandeman\'s flagship estate with stunning panoramic views over the river. Modern tasting room. Tours and tastings €15-50. The drive there alone is worth it.', address: 'Valença do Douro, 5120-496, Portugal', bestTime: 'Late morning' },
    { id: 'dv-quinta-pacheca', name: 'Quinta da Pacheca', type: 'Wine Hotel & Estate', neighborhood: 'Lamego', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Quinta_da_Pacheca.jpg/800px-Quinta_da_Pacheca.jpg', description: 'Historic estate (since 1738). Famous for the wine barrel hotel rooms shaped like giant casks in the vineyard. Restaurant on site. Allow 3 hours.', address: 'R. do Relógio do Sol 261, 5100-424 Lamego, Portugal', bestTime: 'Lunch + tasting' },
    { id: 'dv-river-cruise', name: 'Douro River Cruise', type: 'Boat Trip', neighborhood: 'Régua to Pinhão', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Douro_river_cruise.jpg/800px-Douro_river_cruise.jpg', description: 'Terraced vineyards are most spectacular from the water. Day cruises run from Porto (~12 hrs round trip with train return) or shorter from Régua to Pinhão.', address: 'Cais da Régua, 5050-237 Peso da Régua, Portugal', bestTime: 'Régua to Pinhão (~2 hrs)' },
    { id: 'dv-mateus', name: 'Mateus Palace', type: 'Baroque Palace', neighborhood: 'Vila Real', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Casa_de_Mateus.jpg/800px-Casa_de_Mateus.jpg', description: '18th-century baroque palace immortalized on the Mateus Rosé wine label. Beautiful gardens, ornate interior. Pair with a winery for variety.', address: 'Casa de Mateus, 5000-291 Vila Real, Portugal', bestTime: 'Morning' },
  ],
};

export const RESTAURANTS = {
  marrakech: [
    { id: 'mk-r-nomad', name: 'Nomad', cuisine: 'Modern Moroccan', priceLevel: '$$', neighborhood: 'Medina (Place des Épices)', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Marrakech_Restaurant_Rooftop.jpg/800px-Marrakech_Restaurant_Rooftop.jpg', description: 'Stylish rooftop overlooking the spice market. Reimagined Moroccan classics — beetroot tagine, lamb shoulder, fresh salads. Reservations essential.', address: '1 Derb Aarjane, Place des Épices, Marrakech 40000, Morocco' },
    { id: 'mk-r-jardin', name: 'Le Jardin', cuisine: 'Mediterranean / Moroccan', priceLevel: '$$', neighborhood: 'Medina', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Marrakech_Riad_Garden.jpg/800px-Marrakech_Riad_Garden.jpg', description: 'Verdant green-tiled garden inside a 17th-century riad. Light Mediterranean alongside Moroccan classics. Great for a long lazy lunch. Resident tortoises.', address: '32 Souk El Jeld Sidi Abdelaziz, Marrakech 40000, Morocco' },
    { id: 'mk-r-naranj', name: 'Naranj', cuisine: 'Lebanese', priceLevel: '$$', neighborhood: 'Medina', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Lebanese_food_mezze.jpg/800px-Lebanese_food_mezze.jpg', description: 'Excellent Lebanese mezze in a calm setting. A welcome relief from constant Moroccan food. Great hummus, kibbeh, fattoush. Vegetarian-friendly.', address: '84 R. Riad Zitoun Jdid, Marrakech 40000, Morocco' },
    { id: 'mk-r-plus61', name: '+61', cuisine: 'Australian / Modern', priceLevel: '$$', neighborhood: 'Gueliz', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Modern_restaurant_interior.jpg/800px-Modern_restaurant_interior.jpg', description: 'Australian chef\'s ingredient-driven menu in modern Gueliz. Wood-fired everything, seasonal Moroccan produce, exceptional natural wine list.', address: '96 R. Mohammed El Beqal, Marrakech 40000, Morocco' },
    { id: 'mk-r-tobsil', name: 'Dar Yacout', cuisine: 'Traditional Moroccan', priceLevel: '$$$', neighborhood: 'Medina', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Moroccan_tagine_dish.jpg/800px-Moroccan_tagine_dish.jpg', description: 'Iconic palace restaurant since 1987 — set 5-course menu in a stunning courtyard riad with rooftop views. The "do this once" Marrakech meal.', address: '79 Sidi Ahmed Soussi, Marrakech 40000, Morocco' },
    { id: 'mk-r-cafeclock', name: 'Café Clock', cuisine: 'Moroccan / Café', priceLevel: '$', neighborhood: 'Kasbah', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Moroccan_cafe_interior.jpg/800px-Moroccan_cafe_interior.jpg', description: 'Casual all-day spot known for the camel burger (yes really, and yes good), traditional plates, and cultural events. Family-friendly.', address: '224 Derb Chtouka, Marrakech 40000, Morocco' },
    { id: 'mk-r-grand-cafe', name: 'Grand Café de la Poste', cuisine: 'French / Brasserie', priceLevel: '$$', neighborhood: 'Gueliz', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/French_brasserie_interior.jpg/800px-French_brasserie_interior.jpg', description: 'Restored 1920s colonial-era post office turned brasserie. Steak frites, oysters, classic French. Wide veranda, ceiling fans, white linens.', address: 'Boulevard El Mansour Eddahbi, Marrakech 40020, Morocco' },
  ],
  lisbon: [
    { id: 'ls-r-cervejaria', name: 'Cervejaria Ramiro', cuisine: 'Seafood', priceLevel: '$$', neighborhood: 'Intendente', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Portuguese_seafood_platter.jpg/800px-Portuguese_seafood_platter.jpg', description: 'Lisbon\'s most beloved seafood institution since 1956 — Anthony Bourdain\'s favorite. Order percebes, tiger prawns, and finish with the prego sandwich.', address: 'Av. Almirante Reis 1H, 1150-007 Lisboa, Portugal' },
    { id: 'ls-r-prado', name: 'Prado', cuisine: 'Modern Portuguese / Farm-to-Table', priceLevel: '$$$', neighborhood: 'Baixa', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Modern_Portuguese_food.jpg/800px-Modern_Portuguese_food.jpg', description: 'Chef António Galapito\'s ingredient-obsessed restaurant focused on small-producer sourcing. Light, vegetable-forward. Among Portugal\'s best natural wine lists.', address: 'Tv. Pedras Negras 2, 1100-404 Lisboa, Portugal' },
    { id: 'ls-r-tasca', name: 'Taberna da Rua das Flores', cuisine: 'Tapas / Modern Portuguese', priceLevel: '$$', neighborhood: 'Chiado', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Portuguese_petiscos.jpg/800px-Portuguese_petiscos.jpg', description: 'Tiny, blackboard-menu spot — changes daily based on the market. One of the city\'s most-loved petiscos spots. No reservations, arrive at opening.', address: 'R. das Flores 103, 1200-194 Lisboa, Portugal' },
    { id: 'ls-r-pap-acorda', name: 'Pap\'Açorda', cuisine: 'Traditional Portuguese', priceLevel: '$$', neighborhood: 'Time Out Market', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Portuguese_acorda.jpg/800px-Portuguese_acorda.jpg', description: 'Legendary açorda (bread-thickened seafood stew) since 1981. Now in the Time Out Market. Order seafood açorda + chocolate mousse. Quintessential Portuguese.', address: 'Mercado da Ribeira, Av. 24 de Julho 49, 1200-479 Lisboa, Portugal' },
    { id: 'ls-r-zambeze', name: 'Zambeze', cuisine: 'Mozambican / Portuguese', priceLevel: '$$', neighborhood: 'Mouraria', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Mozambican_food.jpg/800px-Mozambican_food.jpg', description: 'Rooftop with sweeping castle views and a Mozambican-Portuguese menu reflecting colonial culinary history. Piri-piri prawns are the signature.', address: 'Cç. Marquês de Tancos 1, 1100-340 Lisboa, Portugal' },
    { id: 'ls-r-bairro-avillez', name: 'Bairro do Avillez', cuisine: 'Modern Portuguese', priceLevel: '$$', neighborhood: 'Chiado', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Modern_Lisbon_restaurant.jpg/800px-Modern_Lisbon_restaurant.jpg', description: 'José Avillez\'s casual concept (his Michelin-starred is Belcanto). Several themed rooms — taberna, mercearia, páteo. Good for groups with mixed tastes.', address: 'R. Nova da Trindade 18, 1200-303 Lisboa, Portugal' },
    { id: 'ls-r-pesca', name: 'A Cevicheria', cuisine: 'Peruvian-Portuguese Fusion', priceLevel: '$$', neighborhood: 'Príncipe Real', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Ceviche_dish.jpg/800px-Ceviche_dish.jpg', description: 'Tiny, hard-to-get-into ceviche bar with a giant octopus on the ceiling. Chef Kiko Martins fuses Peruvian technique with Portuguese fish. No reservations.', address: 'R. Dom Pedro V 129, 1250-048 Lisboa, Portugal' },
    { id: 'ls-r-manteigaria', name: 'Manteigaria', cuisine: 'Pastelaria', priceLevel: '$', neighborhood: 'Chiado / multiple', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Pastel_de_nata.jpg/800px-Pastel_de_nata.jpg', description: 'Many locals\' favorite pastel de nata, even over Pastéis de Belém. Watch them being made. Perfect crackly tops, custardy middles. Multiple locations.', address: 'R. do Loreto 2, 1200-242 Lisboa, Portugal' },
  ],
  sintra: [
    { id: 'sn-r-tacho', name: 'Tacho Real', cuisine: 'Traditional Portuguese', priceLevel: '$$', neighborhood: 'Sintra Vila', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Portuguese_traditional_food.jpg/800px-Portuguese_traditional_food.jpg', description: 'Classic Portuguese family-run spot in the historic center. Bacalhau à Brás, octopus rice, slow-roasted lamb. Stone walls, copper pots. Reserve.', address: 'R. da Ferraria 4, 2710-555 Sintra, Portugal' },
    { id: 'sn-r-incomum', name: 'Incomum by Luís Santos', cuisine: 'Modern Portuguese', priceLevel: '$$', neighborhood: 'Sintra Vila', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Modern_Portuguese_plating.jpg/800px-Modern_Portuguese_plating.jpg', description: 'Refined contemporary Portuguese cooking, exceptionally well-priced. The lunch tasting menu is one of the best food-value experiences in Portugal.', address: 'R. Dr. Alfredo da Costa 22, 2710-523 Sintra, Portugal' },
    { id: 'sn-r-piriquita', name: 'Piriquita', cuisine: 'Pastelaria', priceLevel: '$', neighborhood: 'Sintra Vila', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Travesseiros_de_Sintra.jpg/800px-Travesseiros_de_Sintra.jpg', description: 'Birthplace of the travesseiros de Sintra — flaky almond-filled pastries. Open since 1862. Also try the queijadas (cheese pastries). Two locations.', address: 'R. das Padarias 1, 2710-603 Sintra, Portugal' },
  ],
  porto: [
    { id: 'po-r-cantinho', name: 'Cantinho do Avillez', cuisine: 'Modern Portuguese', priceLevel: '$$', neighborhood: 'Centro', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Porto_restaurant_interior.jpg/800px-Porto_restaurant_interior.jpg', description: 'José Avillez\'s casual Porto outpost. Excellent Portuguese with creative twists. Grilled octopus, exploding olives, classic petiscos. Reliable and central.', address: 'R. de Mouzinho da Silveira 166, 4050-417 Porto, Portugal' },
    { id: 'po-r-flow', name: 'Flow Restaurant', cuisine: 'Modern European', priceLevel: '$$', neighborhood: 'Cedofeita', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Modern_european_dish.jpg/800px-Modern_european_dish.jpg', description: 'Stylish bistro in trendy Cedofeita. Inventive seasonal menu, strong on local seafood and vegetables. Great brunch on weekends. Excellent natural wines.', address: 'R. da Conceição 63, 4050-214 Porto, Portugal' },
    { id: 'po-r-caixa', name: 'A Caixa Negra', cuisine: 'Tapas / Wine Bar', priceLevel: '$$', neighborhood: 'Bonfim', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Portuguese_wine_bar.jpg/800px-Portuguese_wine_bar.jpg', description: 'Small wine bar in an up-and-coming neighborhood. Incredible Portuguese wines you won\'t find elsewhere, paired with charcuterie and small plates.', address: 'R. de São Vítor 36, 4000-518 Porto, Portugal' },
    { id: 'po-r-pedro', name: 'Pedro Lemos', cuisine: 'Michelin Star', priceLevel: '$$$$', neighborhood: 'Foz', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Michelin_star_tasting_menu.jpg/800px-Michelin_star_tasting_menu.jpg', description: '1-Michelin-starred restaurant in a 19th-century townhouse. Sophisticated Portuguese tasting menus, exceptional service. Tasting menus from ~€150.', address: 'R. do Padre Luís Cabral 974, 4150-459 Porto, Portugal' },
    { id: 'po-r-tasca', name: 'Tasca do Bairro', cuisine: 'Traditional / Petiscos', priceLevel: '$', neighborhood: 'Bonfim', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Portuguese_tasca.jpg/800px-Portuguese_tasca.jpg', description: 'No-frills tasca where locals outnumber tourists. Wood-fired sardines, codfish cakes, local wines by the jug. The real Porto food experience.', address: 'R. de Pinto Bessa 134, 4300-415 Porto, Portugal' },
    { id: 'po-r-majestic', name: 'Café Majestic', cuisine: 'Café / Pastries', priceLevel: '$$', neighborhood: 'Centro (Santa Catarina)', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Cafe_Majestic_Porto.jpg/800px-Cafe_Majestic_Porto.jpg', description: '1921 Belle Époque café where J.K. Rowling reportedly wrote part of Harry Potter. Stunning art nouveau. Skip the meals, do coffee and pastries.', address: 'R. de Santa Catarina 112, 4000-442 Porto, Portugal' },
  ],
  douro: [
    { id: 'dv-r-doc', name: 'DOC', cuisine: 'Modern Portuguese / Wine Pairing', priceLevel: '$$$', neighborhood: 'Folgosa do Douro', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Douro_river_restaurant.jpg/800px-Douro_river_restaurant.jpg', description: 'Chef Rui Paula\'s flagship on a deck cantilevered over the Douro. Stunning vineyard views. Modern Portuguese with extraordinary wine pairings. Reserve weeks ahead.', address: 'Estrada Nacional 222, 5110-204 Folgosa, Portugal' },
    { id: 'dv-r-pacheca', name: 'Restaurante Quinta da Pacheca', cuisine: 'Wine Country Portuguese', priceLevel: '$$', neighborhood: 'Lamego', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Wine_country_lunch.jpg/800px-Wine_country_lunch.jpg', description: 'Restaurant inside the historic Quinta da Pacheca wine estate. Lunch with vineyard views, classic Portuguese dishes elevated with their own wines.', address: 'R. do Relógio do Sol 261, 5100-424 Lamego, Portugal' },
    { id: 'dv-r-castas', name: 'Castas e Pratos', cuisine: 'Modern Portuguese', priceLevel: '$$', neighborhood: 'Peso da Régua', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Modern_portuguese_wine_food.jpg/800px-Modern_portuguese_wine_food.jpg', description: 'Inside a beautifully restored former railway warehouse in Régua. One of the deepest Douro wine lists. Modern plates designed to pair with the bottles.', address: 'R. José Vasques Osório, 5050-280 Peso da Régua, Portugal' },
    { id: 'dv-r-cozinhasoares', name: 'Cozinha das Soares', cuisine: 'Traditional Wine Country', priceLevel: '$$', neighborhood: 'Pinhão', photo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Traditional_portuguese_meal.jpg/800px-Traditional_portuguese_meal.jpg', description: 'Family-run in Pinhão village. Traditional Trás-os-Montes — slow-cooked meats, posta de vitela, seasonal vegetables. Walk-in friendly. Honest and delicious.', address: 'R. do Comércio, 5085-201 Pinhão, Portugal' },
  ],
};
